export type RoleType =
  | "SUPERADMIN"
  | "ADMIN"
  | "STAFF"
  | "CLIENT"
  | "TECHNICAL_MANAGER";

export enum Role {
  SUPERADMIN = "SUPERADMIN",
  ADMIN = "ADMIN",
  STAFF = "STAFF",
  CLIENT = "CLIENT",
  TECHNICAL_MANAGER = "TECHNICAL_MANAGER",
}
